# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-26 03:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('wagtailcore', '0040_page_draft_title'),
        ('fabrication', '0003_auto_20171006_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'fabrication categories',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='FabricationProjectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('description', wagtail.wagtailcore.fields.RichTextField()),
                ('categories', modelcluster.fields.ParentalManyToManyField(blank=True, to='fabrication.FabricationCategory')),
                ('list_image', models.ForeignKey(blank=True, help_text='Minimum 800px wide & 800px tall', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name': 'Fabrication Project',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FabricationProjectPageGalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('image', models.ForeignKey(help_text='Minimum 1600px wide & 608px tall', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabrication_project_gallery_images', to='fabrication.FabricationProjectPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='fabricationpage',
            name='fabrication_title',
        ),
        migrations.RemoveField(
            model_name='fabricationpage',
            name='process_content',
        ),
        migrations.RemoveField(
            model_name='fabricationpage',
            name='process_title',
        ),
        migrations.RemoveField(
            model_name='fabricationpage',
            name='production_content',
        ),
        migrations.RemoveField(
            model_name='fabricationpage',
            name='production_title',
        ),
        migrations.AlterField(
            model_name='fabricationpage',
            name='fabrication_content',
            field=wagtail.wagtailcore.fields.StreamField((('item_list', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock()), ('text', wagtail.wagtailcore.blocks.TextBlock()))), icon='list-ul')), ('numbered_item_list', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock()), ('text', wagtail.wagtailcore.blocks.TextBlock()))), icon='list-ol')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow')), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('video', wagtail.wagtailembeds.blocks.EmbedBlock()))),
        ),
        migrations.AddField(
            model_name='fabricationcategory',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabrication_categories', to='fabrication.FabricationPage'),
        ),
    ]
