# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-26 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrication', '0006_auto_20210726_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricationprojectpage',
            name='items',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
