# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-26 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrication', '0012_remove_fabricationmaterialpage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricationpage',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL from a video streaming service such as Vimeo.'),
        ),
    ]
