# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-27 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('fabrication', '0013_fabricationpage_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabricationpage',
            name='video_url',
        ),
        migrations.AddField(
            model_name='fabricationpage',
            name='video_hd_url',
            field=models.URLField(blank=True, help_text='High Definition URL from a video streaming service such as Vimeo.'),
        ),
        migrations.AddField(
            model_name='fabricationpage',
            name='video_poster',
            field=models.ForeignKey(blank=True, help_text='Still frame from video to show while loading', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='fabricationpage',
            name='video_sd_url',
            field=models.URLField(blank=True, help_text='Standard Definition URL from a video streaming service such as Vimeo.'),
        ),
    ]
