# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_auto_20170522_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='website',
            field=models.URLField(blank=True, help_text='Website URL'),
        ),
    ]
