# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0003_projectpage_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='design.ProjectPage')),
            ],
        ),
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='design.ProjectPage')),
            ],
        ),
        migrations.RemoveField(
            model_name='projectpageclient',
            name='client',
        ),
        migrations.RemoveField(
            model_name='projectpageclient',
            name='page',
        ),
        migrations.RemoveField(
            model_name='projectpagecollaborator',
            name='collaborator',
        ),
        migrations.RemoveField(
            model_name='projectpagecollaborator',
            name='page',
        ),
        migrations.DeleteModel(
            name='ProjectPageClient',
        ),
        migrations.DeleteModel(
            name='ProjectPageCollaborator',
        ),
    ]
