# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 15:19
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0005_auto_20170605_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='page',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='design.ProjectPage'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='page',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='design.ProjectPage'),
        ),
    ]
