# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0006_auto_20170616_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpagegalleryimage',
            name='video',
            field=models.URLField(blank=True, help_text='URL from a video streaming service such as Vimeo. Video will take precedence over an image if both are included.'),
        ),
        migrations.AlterField(
            model_name='projectpagegalleryimage',
            name='image',
            field=models.ForeignKey(help_text='Slideshow image. Include either one image or one video per slideshow item.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
    ]
