# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0008_auto_20170731_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='date',
            field=models.CharField(blank=True, help_text='Project Date / Season', max_length=255),
        ),
    ]
