# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-25 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('design', '0009_auto_20170731_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='list_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
    ]
