# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0011_auto_20170925_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPageVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('video', models.URLField(blank=True, help_text='URL from a video streaming service such as Vimeo.')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='design.ProjectPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='projectpagegalleryimage',
            name='video',
        ),
        migrations.AlterField(
            model_name='projectpagegalleryimage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Slideshow image.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
    ]
