# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0014_auto_20171004_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'ordering': ['sort_order'], 'verbose_name_plural': 'project categories'},
        ),
    ]
