# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 00:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0016_auto_20171006_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='collaborator',
            options={'ordering': ['sort_order']},
        ),
    ]
