# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0017_auto_20171013_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='photo_credit',
            field=models.CharField(blank=True, help_text='Add credits for photography here.', max_length=255),
        ),
    ]
