# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20170510_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='image',
            field=models.ForeignKey(help_text=b'Minimum 1600px wide & 608px tall', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
    ]
