# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-26 03:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20171006_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='image',
            field=models.ForeignKey(help_text='Minimum 1600px wide & 608px tall', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
    ]
