# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-01 14:07
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20210726_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='job_posting',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
    ]
