# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-05-22 15:06
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_contactpage_job_posting'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'image1', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'image2', wagtail.wagtailimages.blocks.ImageChooserBlock())], blank=True, help_text=b'Page Content', null=True),
        ),
    ]
