# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-05-22 15:30
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_contactpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'two_images', wagtail.wagtailcore.blocks.StructBlock([(b'image1', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'image2', wagtail.wagtailimages.blocks.ImageChooserBlock())])), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock(template=b'press/blocks/image.html')), (b'image_gallery', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'caption', wagtail.wagtailcore.blocks.TextBlock(required=False))]), icon=b'image', label=b'Image Slideshow')), (b'video', wagtail.wagtailembeds.blocks.EmbedBlock())], blank=True, help_text=b'Page Content', null=True),
        ),
    ]
