# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-10-10 13:10
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_remove_contactpage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('two_images', wagtail.wagtailcore.blocks.StructBlock((('image1', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('image2', wagtail.wagtailimages.blocks.ImageChooserBlock())))), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock(template='press/blocks/image.html')), ('image_gallery', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('caption', wagtail.wagtailcore.blocks.TextBlock(required=False)))), icon='image', label='Image Slideshow')), ('video', wagtail.wagtailembeds.blocks.EmbedBlock())), blank=True, help_text='Page Content', null=True),
        ),
    ]
