# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 13:26
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_auto_20170510_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilepagecollaborator',
            old_name='client',
            new_name='collaborator',
        ),
        migrations.AlterField(
            model_name='profilepageclient',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_clients', to='profile.ProfilePage'),
        ),
        migrations.AlterField(
            model_name='profilepagecollaborator',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_collaborators', to='profile.ProfilePage'),
        ),
    ]
