# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0007_profilepageplaceholderimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepage',
            name='image',
            field=models.ForeignKey(help_text='Minimum 800px wide & 800px tall', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='profilepage',
            name='image',
            field=models.ForeignKey(help_text='Minimum 1600px wide & 608px tall', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
    ]
