# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('home', '0002_firminformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_tile_url', models.URLField()),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='homepagegalleryitem',
            name='theme',
            field=models.IntegerField(choices=[(1, 'Dark'), (2, 'Light')], default=1),
        ),
    ]
