# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170921_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firminformation',
            name='facebook',
            field=models.URLField(blank=True, help_text='Facebook page URL'),
        ),
        migrations.AlterField(
            model_name='firminformation',
            name='instagram',
            field=models.CharField(blank=True, help_text='Instagram username, without the @', max_length=255),
        ),
        migrations.AlterField(
            model_name='firminformation',
            name='twitter',
            field=models.CharField(blank=True, help_text='Twitter username, without the @', max_length=255),
        ),
    ]
