# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20171004_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagegalleryitem',
            name='theme',
            field=models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='light', max_length=255),
        ),
    ]
