# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20171006_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagegalleryitem',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Minimum 1920px wide', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
