# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-13 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20171006_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagegalleryitem',
            name='video_hd_url',
            field=models.URLField(blank=True, help_text='High Definition URL from a video streaming service such as Vimeo.'),
        ),
        migrations.AddField(
            model_name='homepagegalleryitem',
            name='video_sd_url',
            field=models.URLField(blank=True, help_text='Standard Definition URL from a video streaming service such as Vimeo.'),
        ),
    ]
