# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-05-22 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('home', '0009_auto_20210813_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Farm name', max_length=255)),
                ('address_1', models.CharField(blank=True, max_length=255)),
                ('address_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, help_text='Email address to display on site.', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Phone number to display on site.', max_length=255)),
                ('fax', models.CharField(blank=True, help_text='Fax number to display on site.', max_length=255)),
                ('twitter', models.CharField(blank=True, help_text='Twitter username, without the @', max_length=255)),
                ('facebook', models.URLField(blank=True, help_text='Facebook page URL')),
                ('instagram', models.CharField(blank=True, help_text='Instagram username, without the @', max_length=255)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
