# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 13:36
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_auto_20170522_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchprojectpage',
            name='description',
            field=wagtail.wagtailcore.fields.RichTextField(),
        ),
    ]
