# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('research', '0003_auto_20170925_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchprojectpage',
            name='additional_details',
            field=wagtail.wagtailcore.fields.StreamField([(b'subheading', wagtail.wagtailcore.blocks.CharBlock(classname=b'title', icon=b'title')), (b'text', wagtail.wagtailcore.blocks.RichTextBlock(features=[b'bold', b'italic'], icon=b'pilcrow'))], blank=True),
        ),
        migrations.AddField(
            model_name='researchprojectpage',
            name='list_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='researchprojectpage',
            name='main_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='researchprojectpage',
            name='subtitle',
            field=wagtail.wagtailcore.fields.StreamField([(b'subheading', wagtail.wagtailcore.blocks.CharBlock(classname=b'title', icon=b'title')), (b'text', wagtail.wagtailcore.blocks.RichTextBlock(features=[b'bold', b'italic'], icon=b'pilcrow'))], blank=True),
        ),
    ]
