# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 01:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0008_auto_20171004_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedResearchProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_projects', to='research.ResearchPage')),
                ('research_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='research.ResearchProjectPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
