# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 14:09
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0009_featuredresearchproject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchpage',
            name='intro',
        ),
        migrations.AlterField(
            model_name='featuredresearchproject',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_research_projects', to='research.ResearchPage'),
        ),
    ]
