# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0010_auto_20171005_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchprojectpage',
            name='list_image',
            field=models.ForeignKey(blank=True, help_text='Minimum 800px wide & 800px tall', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='researchprojectpage',
            name='main_image',
            field=models.ForeignKey(help_text='Minimum 1600px wide & 800px tall', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='researchprojectpagegalleryimage',
            name='image',
            field=models.ForeignKey(help_text='Minimum 1160px wide & 1160px tall', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
    ]
