# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-26 03:31
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0011_auto_20171006_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchprojectpage',
            name='additional_details',
            field=wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='title', icon='title')), ('subheading', wagtail.wagtailcore.blocks.CharBlock(classname='title', icon='title')), ('text', wagtail.wagtailcore.blocks.RichTextBlock(features=['bold', 'italic'], icon='pilcrow'))), blank=True),
        ),
        migrations.AlterField(
            model_name='researchprojectpage',
            name='subtitle',
            field=wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='title', icon='title')), ('subheading', wagtail.wagtailcore.blocks.CharBlock(classname='title', icon='title')), ('text', wagtail.wagtailcore.blocks.RichTextBlock(features=['bold', 'italic'], icon='pilcrow'))), blank=True),
        ),
    ]
