# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 01:30
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0014_auto_20171003_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitempage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'heading', wagtail.wagtailcore.blocks.CharBlock(classname='title', icon='title')), (b'subheading', wagtail.wagtailcore.blocks.CharBlock(classname='title', icon='title')), (b'text', wagtail.wagtailcore.blocks.RichTextBlock(features=['bold', 'italic', 'ul', 'ol', 'link'], icon='pilcrow')), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock(template='press/blocks/image.html')), (b'image_gallery', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'caption', wagtail.wagtailcore.blocks.TextBlock(required=False))]), icon='image', label='Image Slideshow')), (b'video', wagtail.wagtailembeds.blocks.EmbedBlock()), (b'project', wagtail.wagtailcore.blocks.PageChooserBlock(target_model=['design.ProjectPage'], template='design/blocks/related_project.html')), (b'pullquote', wagtail.wagtailcore.blocks.BlockQuoteBlock()), (b'document', wagtail.wagtaildocs.blocks.DocumentChooserBlock(icon='doc-full-inverse'))], blank=True, help_text='Content for FGS published articles. Optional'),
        ),
    ]
