# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0016_auto_20171004_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='page',
        ),
    ]
