# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0017_remove_award_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitempage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Teaser Image. Minimum 400px wide & 500px tall', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='presspage',
            name='placeholder_image',
            field=models.ForeignKey(blank=True, help_text='Press article placeholder image. Minimum 400px wide & 500px tall.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
    ]
